
// This file was auto-generated by ML.NET Model Builder. 

using MLModel1_ConsoleApp;
using System.IO;

// Create single instance of sample data from first line of dataset for model input
var imageBytes = File.ReadAllBytes(@"D:\Folder Claudiu\Facultate FII UAIC\Anul 3 (2023 - 2024)\Licență\LingoLabs-Licenta\MachineLearning - Text Detection (Python)\ML_Images-SmallLetters\without_train_or_test\a\image_10036.jpg");
MLModel1.ModelInput sampleData = new MLModel1.ModelInput()
{
    ImageSource = imageBytes,
};

// Make a single prediction on the sample data and print results.
var sortedScoresWithLabel = MLModel1.PredictAllLabels(sampleData);
Console.WriteLine($"{"Class",-40}{"Score",-20}");
Console.WriteLine($"{"-----",-40}{"-----",-20}");

foreach (var score in sortedScoresWithLabel)
{
    Console.WriteLine($"{score.Key,-40}{score.Value,-20}");
}
